### PR TITLE
#55: Unified the interfaces for creation of dB Objects

### LINKED ISSUE #55: Unify the interface for creating database objects
Most of the database objects are instantiated with and `com.exasol.db.Identifier`, as in https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlUser.java#L18

Some other objects do the same but change the API, as in https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlSchema.java#L18

This makes the API harder to use. We should unify this.

### PR DESCRIPTION
**Pull request by priyank0910**
Closes #55

### CODE REVIEW

**Comment by priyank0910** [comment]
@chiaradiamarcelo, @jakobbraun Could you please review the PR. Let me know if I have missed any class where this change might be applicable.

**Review by chiaradiamarcelo — COMMENTED** [review]
hey @priyank0910 ,
thanks a lot for the contribution, it looks good!

There are a few more cases where this should be addressed:
https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolUser.java#L23
https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolUser.java#L36
https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/mysql/MySqlUser.java#L35
https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolSchema.java#L27
https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/exasol/VirtualSchema.java#L44
https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/exasol/ConnectionDefinition.java#L32
https://github.com/exasol/test-db-builder-java/blob/main/src/main/java/com/exasol/dbbuilder/dialects/exasol/ConnectionDefinition.java#L49

thanks!

**Comment by priyank0910** [comment]
@chiaradiamarcelo thanks. I'll check and update the PR.

**Comment by priyank0910** [comment]
Hi @chiaradiamarcelo, I have updated the PR. Please check. If the changes are fine then please merge the PR also as I am not authorized to merge it. Thanks!!!

**Review by chiaradiamarcelo — APPROVED** [review]

**Comment by chiaradiamarcelo** [comment]
hey @priyank0910 , it looks great. Thanks a lot for the contribution!

**Pull request merged**
